specVersion: '0.2.0'

name: 'subscan-multisig'
version: '0.0.1'
description: ''
repository: ''

schema:
  file: './schema.graphql'

dataSources:
  - kind: substrate/Runtime
    # startBlock: 1000
    # startBlock: 1392128
    startBlock: 6141000 # Darwinia
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler

network:
  # Polkadot
  # genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  # endpoint: wss://rpc.polkadot.io

  # KSM
  # genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  # endpoint: wss://kusama.api.onfinality.io/public-ws

  # Darwinia
  genesisHash: '0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8'
  endpoint: wss://rpc.darwinia.network

  # CRAB
  # endpoint: wss://crab-rpc.darwinia.network

  # pangolin
  # genesisHash: '0xce44bd16fc276f9e457b452577b6c2678e57768260012af127479fed806da7e7'
  # endpoint: wss://pangolin-rpc.darwinia.network/

  chaintypes:
    # file: './pangolin_types.yaml'
    file: './darwinia_types.yaml'
